name = "underarc-bot"
main = "./src/ts/server.ts"
compatibility_date = "2024-08-06"

kv_namespaces = [
    { binding = "agents", id = "c94d8925006d4b96b8574b4043322fec" },
    { binding = "wengines", id = "6e440ed53318461b88dd27411171b784" }
]